---
- id: cljfmt-docker
  name: Lint Clojure
  description: Runs cljfmt Docker image to lint clojure files
  language: docker_image
  types: [clojure]
  entry: allisoncasey327/cljfmt:v0.9.1
  args: [fix]
