default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
    - id: hadolint-docker
      name: Lint Dockerfiles
      description: Runs hadolint Docker image to lint Dockerfiles
      language: docker_image
      types: ["dockerfile"]
      entry: ghcr.io/hadolint/hadolint:v2.10.0
      args: [hadolint, --ignore, DL4006]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
    hooks:
      - id: commitizen
